name: Unit Tests

on:
  push:
  pull_request:

jobs:
  validate:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
        os: ["ubuntu-latest", "windows-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip_cache
      - name: Install depencency
        run: |
          pip install gql gql[aiohttp] gql[websockets] graphql-core asyncio-atexit pytest
      - name: Pytest
        run: |
          python -m pytest tests
